### PR TITLE
Add Livecoin exchange

### LINKED ISSUE #202: [Feature Request] - Add www.livecoin.net on the list of exchanges.

### PR DESCRIPTION
**Pull request by RichyHBM**
This commit resolves #202 and #213 adding support for [Livecoin](https://www.livecoin.net/)

### CODE REVIEW

**Comment by MaciejCiemiega** [comment]
Thanks.
I've modified few things:

1. Use `checkerInfo.getCurrencyPairId()` as `%1$s` while formatting URL instead of `%1$s/%2$s` and using base and counter currencies. Currency pair id is already formatted that way and it comes directly from API response (for example: "BTC/USD")
2. Added bid and ask from ticker
3. Added null checks - I've noticed that one `best_ask` was null. I have no idea which fields are nullable because it's not specified in their API so I've added it to most of them (apart from `last` which is mandatory)

I will include this exchange in next update of Bitcoin Checker.

**Comment by RichyHBM** [comment]
Awesome! :)

**Comment by MaciejCiemiega** [comment]
It is included in 1.6.2 update that I've just released.

**Comment by RichyHBM** [comment]
Awesome, looking forward to getting the update!

**Pull request merged**
