### PR TITLE
New exchange: Binance

### PR DESCRIPTION
**Pull request by sirfoga**
# Fix
- typo in links in `README`

# Add
- [Binance](binance.com) market with few pairs

### CODE REVIEW

**Comment by sirfoga** [comment]
Here are some screenshots:

screenshot_1513180142

screenshot_1513180200

screenshot_1513180208

**Comment by k3nnethl** [comment]
When which this be released? It would be great if you could add Populous token to the Binance exchange. Thanks.

**Comment by sirfoga** [comment]
No one has reviewed this so far ... as for the `Populous` token, when you add the market you can download all the pairs, so if the token is listed in the official `Bitfinex` API then it will be automatically added.

**Comment by madnight** [comment]
@sirfoga razor901 approved the changes, so when does this get merged @MaciejCiemiega ?

**Comment by sirfoga** [comment]
@madnight I have no write rights: I cannot merge the PR ;(

**Comment by MaciejCiemiega** [comment]
Unfortunately this doesn't work. Please read my comment in https://github.com/mobnetic/BitcoinChecker/issues/433

I'm closing it for now. Someone can try writing to them if they plan to provide an API that displayed currency pairs as two separate currencies.

**Pull request closed without merging**
