### PR TITLE
Remove Foxbit due to instability

### PR DESCRIPTION
**Pull request by jpereira**
The exchange www.foxbit.com.br is no longer running over the Blinktrade network as can be seen here https://portaldobitcoin.com/foxbit-lanca-novo-site-plataforma-atrasa-e-blinktrade-vira-rival/

ps: The link is available only in Portuguese.

### CODE REVIEW

**Comment by vjavs** [comment]
Closes #731

**Comment by marcialvieira** [comment]
@jpereira are you sure it's better to remove support instead of using the new API?
It is a widely used exchange in Brazil!
https://foxbit.com.br/wp-content/uploads/2018/07/Documentacao-api-fox-bit.pdf

**Comment by jpereira** [comment]
@marcialvieira are you intend to do that? actually, nowadays nobody trusts in FoxBit. the best thing is to remove it. if tomorrow somebody wants to codify the new support. then it can back as well.

**Comment by marcialvieira** [comment]
NP, I'll do it tomorrow.

**Comment by marcialvieira** [comment]
Ok, now I came to a limitation that will need a real time to implement, BitcoinChecker is not prepared to communicate through websocket as the new FoxBit platform uses, I've never seen any public platform requiring it, but it is not a problem on the side of the FoxBit now, the choice is now in the hands of @MaciejCiemiega.

**Comment by marcialvieira** [comment]
I was looking for the author that implemented this to help us, but it was you (@MaciejCiemiega) by issue #142 of the user @schiavonxv

**Comment by jpereira** [comment]
@marcialvieira That is the thing. can't be fixed easily due to websocket.

**Comment by marcialvieira** [comment]
Oh, I didn't realize you mean that, so BitcoinChecker should became obsolete, since it will be more and more API migration to websockets?

**Comment by jpereira** [comment]
Probably not. for me, BitcoinChecker is the number one. btw, the exchanges should provide both support as Blinktrade does. but, up to you.

**Comment by hanelore** [comment]
I will check. Thanks everybody.

**Comment by jpereira** [comment]
@hanelore any news?

**Comment by hanelore** [comment]
@jpereira Foxbit now works with websocket API only. 

https://docs.foxbit.com.br/EN/index.html

Any solution?

**Pull request merged**
