### PR TITLE
Add Coinapult exchange

### LINKED ISSUE #204: coinapult
can you please coinapult make in the app!?

### PR DESCRIPTION
**Pull request by RichyHBM**
This will resolve #204 by adding support for [coinapult](https://coinapult.com/)

### CODE REVIEW

**Comment by MaciejCiemiega** [comment]
Thanks. I've added also BTC/XAG and BTC/XAU currency pairs.
Btw. Do you have any idea what does the filters mean: "small", "medium", "large", "vip", "vip+", "100", "500", "2000", "5000", "10000" ? Can we use one of them to fetch also bid and ask?

**Comment by RichyHBM** [comment]
From what I could tell, coinapult allows you to buy in bulk in order to get a small discount. I figured for the purpose of the tracker you will want the price if buying a single item

**Comment by ICY-1-Flex-Fraction-Studios** [comment]
Yes thanks that was needed. Can I be sent the code your mentioned in the
first email. Send it in PDF.. Or Adobe. Thanks aging if you need to speak
to me call 5033798987.

Thank You.
Alex. F

Sr. Flex

**Comment by MaciejCiemiega** [comment]
It is included in 1.6.2 update that I've just released.

**Comment by ICY-1-Flex-Fraction-Studios** [comment]
Can you email and explain what is going on?

**Comment by ICY-1-Flex-Fraction-Studios** [comment]
I don't understand how to get my funds out of Bitcoin?!? And it's much much
needed you have no idea. If I can be e-mail what to do or called at
503-379-8987. This is much need. Or any information contained within the
topic.

Thank you,
Alex.F

Sr.Flex

**Comment by ICY-1-Flex-Fraction-Studios** [comment]
Hi mobnetic/BitcoinChec,

I'd like to add you to my professional network on LinkedIn.

- Flex Alexander

Confirm that you know Flex Alexander: https://www.linkedin.com/e/v2?e=0-im3d2jx6-ae&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=HYLWW2OW&invitationId=6118011079420362752








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im3d2jx6-ae&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHEuS-g6KA8ZQAAAVOeKszTd6v1NHzPdL1RuNegxCuETjtpA_dbYJjOG6goBi8TNI5GtZEAnn8yj4NnG5_9rXYE2Wc9w_x7YzJ8Wk4lzR3j-ZcH8KdGdHxPqB4pTjpM6hzxjIJfr4at8NFk25y7-Lr5NICgTvpX8TTsUR3Ehl1kG-Y1qVckEQ97lc5zh34TOzh5&eid=0-im3d2jx6-ae


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im3d2jx6-ae&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by ICY-1-Flex-Fraction-Studios** [comment]
Hi mobnetic/BitcoinChec,

I'd like to add you to my professional network on LinkedIn.

- Flex Alexander

Confirm that you know Flex Alexander: https://www.linkedin.com/e/v2?e=0-im3d2kzd-rx&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=e_xWy_q-&invitationId=6118011074945052672








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im3d2kzd-rx&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFGn2NI5ztHUAAAAVOeKunsUXomlD4xT732h_91tf0R8IwhoDEgdgKh9ehcqF4erXDcqlKmnzVP73FTO_WylYrqOL_jTk32RqTAZokAqumdZ0-JcnI2Vz9DYTQfml0owvrOTW40q1lx3qv6tuWjvIh2OP87tSbq7FRW9qt3jG42LAaF4QJkT_NhVPVC44xrxflu&eid=0-im3d2kzd-rx


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im3d2kzd-rx&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by ICY-1-Flex-Fraction-Studios** [comment]
Flex Alexander Fraction would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-9mx2zy-imdvk47d-ry&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=e_xWy_q-&invitationID=6118011074945052672

View Flex Alexander Fraction&#39;s profile: https://www.linkedin.com/e/v2?e=-9mx2zy-imdvk47d-ry&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=e_xWy_q-&invitationID=6118011074945052672





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-9mx2zy-imdvk47d-ry&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-9mx2zy-imdvk47d-ry&loid=AQGObqiCMsKALQAAAVPEm0BwHi-jgSIU4ydlDNwVASRmHyFR9uSY2ZFRqZACxYJx8sS_oo2lRfdp3jPTXRs87LFplviK1ZOSB6mpgEcdOVHMpvsudUEw7LcrVcsHSvP_I7ZOxBZGfGrrRcpo9WQL3o2kP-5cqwWviFFeyLG1Esk06Q3IOdxAHH-WJ1N5A9zGSAiA

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-9mx2zy-imdvk47d-ry&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by ICY-1-Flex-Fraction-Studios** [comment]
Flex Alexander Fraction would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=dlec4t-imdvja66-bv&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=HYLWW2OW&invitationID=6118011079420362752

View Flex Alexander Fraction&#39;s profile: https://www.linkedin.com/e/v2?e=dlec4t-imdvja66-bv&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=HYLWW2OW&invitationID=6118011079420362752





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=dlec4t-imdvja66-bv&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=dlec4t-imdvja66-bv&loid=AQHyuNY51ueCnwAAAVPEnSebDZrfmtzlr3ANCT_1NifZ8kST5asVxUi-vxkjfkRMts-VSn-PfP5bDnkSs7hAyoow3yyV2dbeR3W8sekYx7STPqvZ5t9rF2BYX686TMtQ-BU8q0RTkPQKKnXH2I5rTped7cqiyiMBO6UazyRo5LY2PZX4DStHNm4p9bzCcisVn2lo

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=dlec4t-imdvja66-bv&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by ICY-1-Flex-Fraction-Studios** [comment]
Flex Alexander Fraction would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=dlec4t-imnvhu5h-pk&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=HYLWW2OW&invitationID=6118011079420362752

View Flex Alexander Fraction&#39;s profile: https://www.linkedin.com/e/v2?e=dlec4t-imnvhu5h-pk&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=HYLWW2OW&invitationID=6118011079420362752





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=dlec4t-imnvhu5h-pk&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=dlec4t-imnvhu5h-pk&loid=AQFODtYVfqGEGQAAAVPpFW5cnHkIaBMnLsYT-Ci13Gksx6tUOFlklXiASvLAkpdH95w-xGyMVao1VGB9SgmWBJjj9iGBbIEGze5eu1gEfv8igw462wfMCIB2R1B4xWIeW0vLM_TkUFJ_kwWtNqf7Io677F2Rp7csz3e1TnzhjPshlzejvjoQ8vWYWJ6LbPtnxJW_

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=dlec4t-imnvhu5h-pk&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by ICY-1-Flex-Fraction-Studios** [comment]
Flex Alexander Fraction would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-9mx2zy-imnviat6-yv&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=e_xWy_q-&invitationID=6118011074945052672

View Flex Alexander Fraction&#39;s profile: https://www.linkedin.com/e/v2?e=-9mx2zy-imnviat6-yv&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=e_xWy_q-&invitationID=6118011074945052672





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-9mx2zy-imnviat6-yv&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-9mx2zy-imnviat6-yv&loid=AQGXwiswl3wZQgAAAVPpFWX3xKENbl7amOvAJWB2cZhhFKdqROG8tjYrQM-zHYU41wbbVPOsi3AAUBojjgbtPRKHFh6amYiSanJwotZSDvBb5ZnIp0vDoQnaoUkLm8-uRZLOsy-Xo6FtRp1418QwCIKdrf5fjgn1YjmbG2uPFc9SxXuJAqIP8y3qSME1YWZLWdAE

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-9mx2zy-imnviat6-yv&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
