### PR TITLE
add bid rate for Ripio

### PR DESCRIPTION
**Pull request by soysergiogomez**
- add bid rate for Ripio
- high value is wrong

### CODE REVIEW

**Comment by MaciejCiemiega** [comment]
Thanks, I've included it in 1.5.10 update, it should be available on Google Play Store within few hours.
Cheers!

**Comment by btcdrak** [comment]
You're adding a lot of new exchanges but still not adding OKCoin Futures support? Why?

**Comment by MaciejCiemiega** [comment]
@btcdrak It probably requires new functionality to be added to app. I've been developing this app for 2 years, completely free, without trying to make any money on it and since some time I only have time for maintaining the current feature set. I mean adding things to DataModule, not to Bitcoin Checker app itself or fixing bugs in app both modules, but not for adding new functionality. Usually every new functionality added requires more maintenance time in the future...

If it would not require adding anything to the Bitcoin Checker app, but only to DataModule - then anyone should feel free to write it and contribute it here.

I hope you understand that. Maybe in some point of time I will have time for adding something new to the app, but I cannot promise anything at this moment.
Greetings.

**Comment by btcdrak** [comment]
@MaciejCiemiega Bitcoin Checker is an amazing application and widely used by the community.

I wonder if the most simple solution would be to add a new exchange OKCoinFutures and add 6 ticker symbols which are all priced in USD. That should fit within your existing architecture more easily. 

reference https://www.okcoin.com/about/rest_api.do#fpapi (GET /api/v1/future_ticker)

Otherwise, would you accept a bounty to do the requisite feature additions?

**Comment by soysergiogomez** [comment]
Thanks to you @MaciejCiemiega ! BitcoinChecker is a great app!

**Comment by mhiller** [comment]
@MaciejCiemiega @btcdrak  i have partially added the okcoin futures for a client that bailed out on payment . Its not a quick thing to do this so i get the hesitation from teh developer If a reasonable bounty was posted and @MaciejCiemiega would accept the pull request, i might be willing to do the work.

**Comment by btcdrak** [comment]
@mhiller I also tried to add futures but quickly realised the architecture was not suited for this particular problem which is why I think the easiest solution would be to add a "new" exchanges, called OKCoinFutures and just add the futures tickers. It would be a lot simpler an incur much no extra technical debt that re-engineering for this edge case (which is all it is).

**Pull request merged**
