### PR TITLE
Add BitMEX exchange

### PR DESCRIPTION
**Pull request by patisson**
It has some futures contracts but they don't quite fit your FuturesMarket model (every contact has its own predefined duration which is coded in its symbol) so I thought it would be easier to just load them all from the exchange as simple tickers.

### CODE REVIEW

**Comment by winai28** [comment]
Ok

**Comment by winai28** [comment]
Hh

**Comment by MaciejCiemiega** [comment]
@patisson The price of BFC in BFXV16 is expressed in what? What is the counter unit there?

**Comment by patisson** [comment]
@MaciejCiemiega The counter unit is 0.1 XBT in this case. That's an example of a BitMEX futures contact. Each has its own rules, sometimes quite tricky, i.e. citing from [here](https://www.bitmex.com/app/contract/BFXV16):

> BFXV16 is a XBT/USD futures contract settling on the .BFX30M Index. Each contract is worth 0.1 XBT per $1 price, currently 0.05663 XBT.

Parsing all these complex rules for every futures contract is beyond the scope of a simple ticker adapter, IMHO. So I derive a pseudo-unit by splitting the name of a contract in half, just to have something to show. But those who trade this instrument on BitMEX will understand no doubt, they just need the numbers. For units and stuff it's better to read a corresponding contract guide on the exchange.

**Comment by STRML** [comment]
See #299

**Pull request closed without merging**
